import "@/styles/globals.css";

import { type Metadata } from "next";
import { Atma } from "next/font/google";

import { Providers } from "@/app/(main)/providers";
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebr";
import { Separator } from "@/components/ui/separator";
import NavBreadcrumbs from "@/components/nav-breadcrumbs";
import { redirect } from "next/navigation";
import { auth } from "@/lib/auth";
import { headers } from "next/headers";
import { db } from "@/server/db";
import { Toaster } from "sonner";

const atma = Atma({
  subsets: ["latin"],
  variable: "--font-atma",
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
    const session = await auth.api.getSession({
      headers: await headers(),
    });
  
  
  
    setInterval(async () => {
      await db.user.findUniqueOrThrow({
        where: {
          id: session!.user.id,
        },
      });
    }, 240000);
  return (
    <html lang="en" className={`${atma.variable}`}>
      <body>
        <Providers>
          <SidebarProvider>
            <AppSidebar />
            <SidebarInset className="flex h-screen flex-col">
              <header className="sticky-top bg-background z-10 flex items-center justify-start gap-2 border-b py-2">
                <SidebarTrigger />
                <Separator
                  orientation="vertical"
                  className="dat-[orientation=vertical]"
                />
                <NavBreadcrumbs />
              </header>

              <main className="flex-1 overflow-y-auto">{children}</main>
            </SidebarInset>
          </SidebarProvider>
          <Toaster/>
        </Providers>
      </body>
    </html>
  );
}
