import "@/styles/globals.css";

import { type Metadata } from "next";
import { Atma } from "next/font/google";

import { Providers } from "@/app/(main)/providers";
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebr";
import { Separator } from "@/components/ui/separator";
import NavBreadcrumbs from "@/components/nav-breadcrumbs";

const atma = Atma({
  subsets: ["latin"],
  variable: "--font-atma",
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${atma.variable}`}>
      <body>
        <Providers>
          <SidebarProvider>
            <AppSidebar />
            <SidebarInset className="flex h-screen flex-col">
              <header className="sticky-top bg-background z-10 flex items-center justify-start gap-2 border-b py-2">
                <SidebarTrigger />
                <Separator
                  orientation="vertical"
                  className="dat-[orientation=vertical] -ml-1"
                />
                <NavBreadcrumbs />
              </header>

              <main className="flex-1 overflow-y-auto">{children}</main>
            </SidebarInset>
          </SidebarProvider>
        </Providers>
      </body>
    </html>
  );
}
